POST https://www.googleapis.com/compute/v1/projects/silken-impulse-217423/zones/us-west1-b/instances
{
  "kind": "compute#instance",
  "name": "leaderboard-generator",
  "zone": "projects/silken-impulse-217423/zones/us-west1-b",
  "machineType": "projects/silken-impulse-217423/zones/us-west1-b/machineTypes/custom-2-4096",
  "displayDevice": {
    "enableDisplay": false
  },
  "metadata": {
    "kind": "compute#metadata",
    "items": [
      {
        "key": "gce-container-declaration",
        "value": "spec:\n  containers:\n    - name: leaderboard-generator\n      image: gcr.io/silken-impulse-217423/leaderboard-generator\n      stdin: true\n      tty: true\n  restartPolicy: Always\n\n# This container declaration format is not public API and may change without notice. Please\n# use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine."
      },
      {
        "key": "google-logging-enabled",
        "value": "true"
      },
      {
        "key": "startup-script",
        "value": "#! /bin/bash\ndocker pull gcr.io/silken-impulse-217423/leaderboard-generator"
      }
    ]
  },
  "tags": {
    "items": []
  },
  "disks": [
    {
      "kind": "compute#attachedDisk",
      "type": "PERSISTENT",
      "boot": true,
      "mode": "READ_WRITE",
      "autoDelete": true,silken-impulse-217423
      "deviceName": "leaderboard-generator",
      "initializeParams": {
        "sourceImage": "projects/cos-cloud/global/images/cos-stable-74-11895-86-0",
        "diskType": "projects/silken-impulse-217423/zones/us-west1-b/diskTypes/pd-standard",
        "diskSizeGb": "10"
      },
      "diskEncryptionKey": {}
    }
  ],
  "canIpForward": false,
  "networkInterfaces": [
    {
      "kind": "compute#networkInterface",
      "subnetwork": "projects/silken-impulse-217423/regions/us-west1/subnetworks/default",
      "accessConfigs": [
        {
          "kind": "compute#accessConfig",
          "name": "External NAT",
          "type": "ONE_TO_ONE_NAT",
          "networkTier": "PREMIUM"
        }
      ],
      "aliasIpRanges": []
    }
  ],
  "description": "",
  "labels": {
    "container-vm": "cos-stable-74-11895-86-0"
  },
  "scheduling": {
    "preemptible": false,
    "onHostMaintenance": "MIGRATE",
    "automaticRestart": true,
    "nodeAffinities": []
  },
  "deletionProtection": false,
  "reservationAffinity": {
    "consumeReservationType": "ANY_RESERVATION"
  },
  "serviceAccounts": [
    {
      "email": "redacted",
      "scopes": [
        "https://www.googleapis.com/auth/cloud-platform"
      ]
    }
  ]
}
